---
version: '3.2'
services:
  nuxt:
    image: ${APP_NAME}-nuxt:latest
    container_name: nuxt
    volumes:
      - type: bind
        source: "${APP_PROJECT_ROOT}"
        target: "/opt/app"
    command: /usr/local/bin/entrypoint.sh --dev
    env_file:
      - "${APP_ENV_PATH}"
    network_mode: host
  nginx:
    image: ${APP_NAME}-nginx:latest
    container_name: nginx
    depends_on:
      - nuxt
    network_mode: host
